sudo: false
language: node_js
node_js:
  - '4.1'
  - '4.0'
  - '0.12'
  - '0.10'
install:
  - npm install -g grunt-cli mocha yo
  - ls -lRa
script:
  - npm install
  - npm test
  - npm link
  - mkdir test_run
  - cd test_run
  - yo gadget --projectName=drupal8 --projectDescription="test drupal8 project" --drupalDistro=drupal --drupalDistroVersion=8.x
  - grunt
